### ISSUE TITLE
Ignore option is not working.

### ISSUE THREAD

**Issue by tonilopezmr** [uncss/uncss#419]
I'm using [Bulma](https://bulma.io/) and I'm trying to ignore `.navbar-burger.is-active` because it's a class you set on runtime, in bulma, `is-active` its used a lot in different components.

I'm using this configuration:

```javascript
options = {
    banner: false,
    csspath: "",
    htmlroot: "./src/",
    ignore: [
         "/\\..+\\.is-active\\.+/", 
        ".navbar-burger.is-active", 
        ".navbar-menu.is-active"
     ], //Added at runtime
    jsdom: {
      userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X)"
    },
    report: true,
    stylesheets: ["style.css"],
    timeout: 1000,
    userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X)"
  };
```

calling to:
```javascript
uncss(files, options, function(error, output) { ... }
```

Here are the elements I want to keep on the CSS output.

```css
.navbar-burger:hover {
    background-color: rgba(0, 0, 0, .05)
}

.navbar-burger.is-active span:nth-child(1) {
    -webkit-transform: translateY(5px) rotate(45deg);
    transform: translateY(5px) rotate(45deg)
}

.navbar-burger.is-active span:nth-child(2) {
    opacity: 0
}

.navbar-burger.is-active span:nth-child(3) {
    -webkit-transform: translateY(-5px) rotate(-45deg);
    transform: translateY(-5px) rotate(-45deg)
}

```

Also, I have tried the ignore selector on the CSS but is not working, ISSUE https://github.com/uncss/uncss/issues/410. It seems it's partially working because for `.navbar-menu.is-active` it's working fine but none for `navbar-burger` don't know why
